# Generated by Django 3.2.4 on 2021-06-24 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_colour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='category',
            new_name='cat',
        ),
    ]
