# Generated by Django 3.2.4 on 2021-06-24 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_category_listing_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='cat',
            new_name='category',
        ),
    ]
